
version: '3'
services: 
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - ./database:/data/db
  frontend:
    build: frontend
    environment: 
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PROTOCOL=http
      - REACT_APP_BACKEND_PORT=8080
      - REACT_APP_BACKEND_ROUTE=api
    ports:
      - '3000:3000'
    volumes: 
      - /frontend/node_modules
      - ./frontend:/app
    depends_on: 
      - backend
  backend:
    build: backend
    ports:
      - '8080:8080'
    environment: 
      - PORT=8080
    volumes:
      - /backend/node_modules
      - ./backend:/app
    depends_on: 
      - mongo